from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from findings.models import FindingRecord


class Command(BaseCommand):
    """
    Carga datos ficticios para presentación.

    Este comando crea:
    - Un usuario demo para iniciar sesión en el frontend.
    - Registros ficticios variados para mostrar lista, filtros, búsqueda y ficha completa.

    Los datos NO corresponden a casos reales.
    Se usan textos neutrales, sin nombres propios, sin imágenes, sin coordenadas reales útiles
    y sin descripciones gráficas por respeto al tema de la aplicación.
    """

    help = "Crea usuario demo y registros ficticios para presentación."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Elimina registros demo existentes y los vuelve a crear.",
        )

    def handle(self, *args, **options):
        User = get_user_model()

        demo_user, _ = User.objects.get_or_create(
            username="admin_demo",
            defaults={
                "email": "admin@registrodigno.local",
                "first_name": "Administradora",
                "last_name": "Demo",
                "is_staff": True,
                "is_superuser": True,
            },
        )

        # Se actualiza siempre para que la cuenta demo funcione aunque ya existiera.
        demo_user.email = "admin@registrodigno.local"
        demo_user.first_name = "Administradora"
        demo_user.last_name = "Demo"
        demo_user.is_staff = True
        demo_user.is_superuser = True
        demo_user.set_password("Demo12345")
        demo_user.save()

        if options["reset"]:
            # Permite limpiar solo los datos de presentación sin tocar registros nuevos creados manualmente.
            FindingRecord.objects.filter(record_code__startswith="RD-DEMO-").delete()
            self.stdout.write("Registros demo anteriores eliminados.")

        records = [
            {
                "record_code": "RD-DEMO-001",
                "status": FindingRecord.RecordStatus.ACTIVE,
                "finding_type": FindingRecord.FindingType.BONE_REMAINS,
                "source": "Registro ficticio para presentación",
                "confidence_level": FindingRecord.ConfidenceLevel.UNCONFIRMED,
                "internal_notes": "Ficha demo completa para mostrar el flujo de lista, detalle y búsqueda.",
                "country": "México",
                "state": "Ciudad de México",
                "municipality": "Tlalpan",
                "locality": "Localidad de prueba",
                "region": "Zona sur",
                "place_type": "Predio",
                "exact_location_restricted": "Dato ficticio restringido para demostración",
                "coordinates_restricted": "Coordenadas omitidas por tratarse de demo",
                "location_notes": "Ubicación ficticia usada solo para probar la visualización de la ficha.",
                "finding_date": "2026-05-20",
                "approximate_time": "10:30:00",
                "date_notes": "Fecha de prueba para presentación.",
                "temporal_range": "Durante la mañana",
                "estimated_individuals": "1",
                "conservation_status": "No determinado",
                "integrity": "Parcial",
                "exposure": "Superficial",
                "general_condition_notes": "Descripción general ficticia, sin información sensible.",
                "estimated_sex": FindingRecord.EstimatedSex.UNKNOWN,
                "estimated_age": "No determinado",
                "estimated_height": "No determinado",
                "estimated_weight": "No determinado",
                "estimated_build": "No determinada",
                "skin_color": "No determinado",
                "hair": "No determinado",
                "facial_hair": "No determinado",
                "eyes": "No determinado",
                "physical_notes": "Datos físicos ficticios para validar la ficha.",
                "tattoos": "Sin dato",
                "scars": "Sin dato",
                "moles": "Sin dato",
                "piercings": "Sin dato",
                "prosthetics": "Sin dato",
                "surgical_marks": "Sin dato",
                "amputations": "Sin dato",
                "distinctive_marks_notes": "Sin señas particulares registradas en la prueba.",
                "braces": "Sin dato",
                "dental_prosthetics": "Sin dato",
                "missing_teeth": "Sin dato",
                "dental_restorations": "Sin dato",
                "dental_notes": "Datos dentales ficticios.",
                "medical_notes": "Sin información médica registrada.",
                "notified_authority": "Pendiente",
                "institutional_folio": "FOLIO-DEMO-001",
                "case_reference": "CASO-DEMO-001",
                "semefo": "SEMEFO demo",
                "institutional_notes": "Registro institucional ficticio para validar visualización.",
                "contact_email": "contacto.demo@example.com",
                "created_by": demo_user,
            },
            {
                "record_code": "RD-DEMO-002",
                "status": FindingRecord.RecordStatus.DRAFT,
                "finding_type": FindingRecord.FindingType.HUMAN_FRAGMENT,
                "source": "Registro ficticio para presentación",
                "confidence_level": FindingRecord.ConfidenceLevel.PROBABLE,
                "internal_notes": "Ficha incompleta en borrador. Sirve para mostrar que no todos los registros nacen completos.",
                "country": "México",
                "state": "Estado de México",
                "municipality": "Nezahualcóyotl",
                "locality": "Zona de prueba",
                "region": "Zona oriente",
                "place_type": "Vía pública",
                "exact_location_restricted": "Dato ficticio restringido",
                "coordinates_restricted": "",
                "location_notes": "Ubicación general ficticia para mostrar otro municipio.",
                "finding_date": "2026-05-18",
                "approximate_time": None,
                "date_notes": "Fecha aproximada.",
                "temporal_range": "Sin hora determinada",
                "estimated_individuals": "Indeterminado",
                "conservation_status": "No determinado",
                "integrity": "Fragmentario",
                "exposure": "No determinado",
                "general_condition_notes": "Registro ficticio sin información sensible.",
                "estimated_sex": FindingRecord.EstimatedSex.UNDETERMINED,
                "estimated_age": "No determinado",
                "estimated_height": "",
                "estimated_weight": "",
                "estimated_build": "",
                "skin_color": "",
                "hair": "",
                "facial_hair": "",
                "eyes": "",
                "physical_notes": "Información física no determinada.",
                "tattoos": "No observable",
                "scars": "No observable",
                "moles": "No observable",
                "piercings": "No observable",
                "prosthetics": "No observable",
                "surgical_marks": "No observable",
                "amputations": "No observable",
                "distinctive_marks_notes": "Sin datos adicionales.",
                "braces": "No observable",
                "dental_prosthetics": "No observable",
                "missing_teeth": "No observable",
                "dental_restorations": "No observable",
                "dental_notes": "No observable.",
                "medical_notes": "",
                "notified_authority": "Pendiente",
                "institutional_folio": "FOLIO-DEMO-002",
                "case_reference": "",
                "semefo": "Pendiente",
                "institutional_notes": "Registro en borrador para demostración.",
                "contact_email": "contacto.demo@example.com",
                "created_by": demo_user,
            },
            {
                "record_code": "RD-DEMO-003",
                "status": FindingRecord.RecordStatus.IN_REVIEW,
                "finding_type": FindingRecord.FindingType.UNKNOWN,
                "source": "Registro ficticio para presentación",
                "confidence_level": FindingRecord.ConfidenceLevel.UNCONFIRMED,
                "internal_notes": "Ficha demo en revisión para probar otro estado del flujo.",
                "country": "México",
                "state": "Querétaro",
                "municipality": "Amealco de Bonfil",
                "locality": "Localidad rural demo",
                "region": "Zona rural",
                "place_type": "Campo",
                "exact_location_restricted": "Dato ficticio restringido",
                "coordinates_restricted": "",
                "location_notes": "Ubicación ficticia para demostrar registros fuera de CDMX.",
                "finding_date": "2026-05-15",
                "approximate_time": "08:15:00",
                "date_notes": "Fecha usada para prueba visual.",
                "temporal_range": "Mañana",
                "estimated_individuals": "1",
                "conservation_status": "No determinado",
                "integrity": "No determinada",
                "exposure": "Superficial",
                "general_condition_notes": "Descripción general ficticia.",
                "estimated_sex": FindingRecord.EstimatedSex.UNKNOWN,
                "estimated_age": "No determinado",
                "estimated_height": "No determinado",
                "estimated_weight": "No determinado",
                "estimated_build": "No determinada",
                "skin_color": "",
                "hair": "",
                "facial_hair": "",
                "eyes": "",
                "physical_notes": "Datos físicos pendientes.",
                "tattoos": "Sin dato",
                "scars": "Sin dato",
                "moles": "Sin dato",
                "piercings": "Sin dato",
                "prosthetics": "Sin dato",
                "surgical_marks": "Sin dato",
                "amputations": "Sin dato",
                "distinctive_marks_notes": "Sin datos adicionales.",
                "braces": "Sin dato",
                "dental_prosthetics": "Sin dato",
                "missing_teeth": "Sin dato",
                "dental_restorations": "Sin dato",
                "dental_notes": "Sin dato.",
                "medical_notes": "Sin información médica registrada.",
                "notified_authority": "Pendiente",
                "institutional_folio": "FOLIO-DEMO-003",
                "case_reference": "CASO-DEMO-003",
                "semefo": "Pendiente",
                "institutional_notes": "Registro demo en revisión.",
                "contact_email": "contacto.demo@example.com",
                "created_by": demo_user,
            },
            {
                "record_code": "RD-DEMO-004",
                "status": FindingRecord.RecordStatus.ACTIVE,
                "finding_type": FindingRecord.FindingType.BODY,
                "source": "Registro ficticio para presentación",
                "confidence_level": FindingRecord.ConfidenceLevel.CONFIRMED,
                "internal_notes": "Ficha demo más completa para mostrar campos físicos, dentales e institucionales.",
                "country": "México",
                "state": "Jalisco",
                "municipality": "Zapopan",
                "locality": "Colonia ficticia",
                "region": "Zona metropolitana",
                "place_type": "Espacio abierto",
                "exact_location_restricted": "Dato restringido no real",
                "coordinates_restricted": "No se usan coordenadas reales en demo",
                "location_notes": "Registro ficticio con información más completa para revisión de ficha.",
                "finding_date": "2026-05-10",
                "approximate_time": "16:45:00",
                "date_notes": "Fecha exacta ficticia.",
                "temporal_range": "Tarde",
                "estimated_individuals": "1",
                "conservation_status": "No determinado",
                "integrity": "Completo para fines de demostración",
                "exposure": "No determinado",
                "general_condition_notes": "Texto neutro para presentación, sin detalles sensibles.",
                "estimated_sex": FindingRecord.EstimatedSex.WOMAN,
                "estimated_age": "25 a 35 años",
                "estimated_height": "1.55 a 1.65 m",
                "estimated_weight": "No determinado",
                "estimated_build": "Media",
                "skin_color": "No determinado",
                "hair": "Cabello oscuro, dato ficticio",
                "facial_hair": "No aplica",
                "eyes": "No determinado",
                "physical_notes": "Características físicas ficticias para demostrar llenado completo.",
                "tattoos": "Tatuaje ficticio descrito de forma general",
                "scars": "Cicatriz ficticia sin ubicación sensible",
                "moles": "Sin dato",
                "piercings": "Perforación ficticia",
                "prosthetics": "Sin dato",
                "surgical_marks": "Sin dato",
                "amputations": "Sin dato",
                "distinctive_marks_notes": "Señas ficticias para mostrar la sección.",
                "braces": "No observable",
                "dental_prosthetics": "Sin dato",
                "missing_teeth": "Sin dato",
                "dental_restorations": "Posible restauración ficticia",
                "dental_notes": "Notas dentales ficticias para presentación.",
                "medical_notes": "Sin información médica registrada.",
                "notified_authority": "Autoridad demo notificada",
                "institutional_folio": "FOLIO-DEMO-004",
                "case_reference": "CASO-DEMO-004",
                "semefo": "Institución demo",
                "institutional_notes": "Ejemplo de registro con mayor nivel de llenado.",
                "contact_email": "contacto.demo@example.com",
                "created_by": demo_user,
            },
            {
                "record_code": "RD-DEMO-005",
                "status": FindingRecord.RecordStatus.ARCHIVED,
                "finding_type": FindingRecord.FindingType.BONE_REMAINS,
                "source": "Registro ficticio para presentación",
                "confidence_level": FindingRecord.ConfidenceLevel.PROBABLE,
                "internal_notes": "Ficha archivada para mostrar que no todos los registros están activos.",
                "country": "México",
                "state": "Puebla",
                "municipality": "Puebla",
                "locality": "",
                "region": "Zona centro",
                "place_type": "Área no especificada",
                "exact_location_restricted": "",
                "coordinates_restricted": "",
                "location_notes": "Registro archivado ficticio.",
                "finding_date": "2026-04-30",
                "approximate_time": None,
                "date_notes": "Fecha histórica ficticia.",
                "temporal_range": "",
                "estimated_individuals": "Indeterminado",
                "conservation_status": "No determinado",
                "integrity": "No determinada",
                "exposure": "No determinada",
                "general_condition_notes": "",
                "estimated_sex": FindingRecord.EstimatedSex.UNKNOWN,
                "estimated_age": "",
                "estimated_height": "",
                "estimated_weight": "",
                "estimated_build": "",
                "skin_color": "",
                "hair": "",
                "facial_hair": "",
                "eyes": "",
                "physical_notes": "",
                "tattoos": "",
                "scars": "",
                "moles": "",
                "piercings": "",
                "prosthetics": "",
                "surgical_marks": "",
                "amputations": "",
                "distinctive_marks_notes": "",
                "braces": "",
                "dental_prosthetics": "",
                "missing_teeth": "",
                "dental_restorations": "",
                "dental_notes": "",
                "medical_notes": "",
                "notified_authority": "",
                "institutional_folio": "FOLIO-DEMO-005",
                "case_reference": "",
                "semefo": "",
                "institutional_notes": "Registro archivado para prueba de filtros.",
                "contact_email": "",
                "created_by": demo_user,
            },
            {
                "record_code": "RD-DEMO-006",
                "status": FindingRecord.RecordStatus.RESTRICTED,
                "finding_type": FindingRecord.FindingType.OTHER,
                "source": "Registro ficticio para presentación",
                "confidence_level": FindingRecord.ConfidenceLevel.UNCONFIRMED,
                "internal_notes": "Ficha restringida para mostrar cómo se verá un registro con datos sensibles.",
                "country": "México",
                "state": "Morelos",
                "municipality": "Cuernavaca",
                "locality": "Zona demo",
                "region": "Zona urbana",
                "place_type": "Lugar no especificado",
                "exact_location_restricted": "Dato sensible ficticio",
                "coordinates_restricted": "Oculto en demo",
                "location_notes": "Registro con ubicación restringida ficticia.",
                "finding_date": "2026-05-12",
                "approximate_time": "12:00:00",
                "date_notes": "Fecha ficticia.",
                "temporal_range": "Mediodía",
                "estimated_individuals": "No aplica",
                "conservation_status": "No aplica",
                "integrity": "No aplica",
                "exposure": "No aplica",
                "general_condition_notes": "Registro de tipo otro, creado para probar variedad.",
                "estimated_sex": FindingRecord.EstimatedSex.UNKNOWN,
                "estimated_age": "",
                "estimated_height": "",
                "estimated_weight": "",
                "estimated_build": "",
                "skin_color": "",
                "hair": "",
                "facial_hair": "",
                "eyes": "",
                "physical_notes": "",
                "tattoos": "",
                "scars": "",
                "moles": "",
                "piercings": "",
                "prosthetics": "",
                "surgical_marks": "",
                "amputations": "",
                "distinctive_marks_notes": "",
                "braces": "",
                "dental_prosthetics": "",
                "missing_teeth": "",
                "dental_restorations": "",
                "dental_notes": "",
                "medical_notes": "",
                "notified_authority": "Pendiente",
                "institutional_folio": "FOLIO-DEMO-006",
                "case_reference": "CASO-DEMO-006",
                "semefo": "",
                "institutional_notes": "Registro ficticio con acceso restringido.",
                "contact_email": "contacto.demo@example.com",
                "created_by": demo_user,
            },
            {
                "record_code": "RD-DEMO-007",
                "status": FindingRecord.RecordStatus.CLOSED,
                "finding_type": FindingRecord.FindingType.UNKNOWN,
                "source": "Registro ficticio para presentación",
                "confidence_level": FindingRecord.ConfidenceLevel.CONFIRMED,
                "internal_notes": "Ficha cerrada para mostrar un registro con flujo concluido dentro de la demo.",
                "country": "México",
                "state": "Hidalgo",
                "municipality": "Pachuca de Soto",
                "locality": "Zona demo",
                "region": "Zona urbana",
                "place_type": "Institución demo",
                "exact_location_restricted": "",
                "coordinates_restricted": "",
                "location_notes": "Registro cerrado ficticio.",
                "finding_date": "2026-05-01",
                "approximate_time": None,
                "date_notes": "Fecha ficticia para demo.",
                "temporal_range": "",
                "estimated_individuals": "1",
                "conservation_status": "No determinado",
                "integrity": "No determinada",
                "exposure": "No determinada",
                "general_condition_notes": "Registro cerrado sin detalles sensibles.",
                "estimated_sex": FindingRecord.EstimatedSex.UNDETERMINED,
                "estimated_age": "No determinado",
                "estimated_height": "No determinado",
                "estimated_weight": "No determinado",
                "estimated_build": "No determinada",
                "skin_color": "",
                "hair": "",
                "facial_hair": "",
                "eyes": "",
                "physical_notes": "Datos no determinados.",
                "tattoos": "Sin dato",
                "scars": "Sin dato",
                "moles": "Sin dato",
                "piercings": "Sin dato",
                "prosthetics": "Sin dato",
                "surgical_marks": "Sin dato",
                "amputations": "Sin dato",
                "distinctive_marks_notes": "",
                "braces": "Sin dato",
                "dental_prosthetics": "Sin dato",
                "missing_teeth": "Sin dato",
                "dental_restorations": "Sin dato",
                "dental_notes": "",
                "medical_notes": "",
                "notified_authority": "Autoridad demo",
                "institutional_folio": "FOLIO-DEMO-007",
                "case_reference": "CASO-DEMO-007",
                "semefo": "Institución demo",
                "institutional_notes": "Registro cerrado para probar filtros por estado.",
                "contact_email": "contacto.demo@example.com",
                "created_by": demo_user,
            },
            {
                "record_code": "RD-DEMO-008",
                "status": FindingRecord.RecordStatus.DRAFT,
                "finding_type": FindingRecord.FindingType.UNKNOWN,
                "source": "Captura incompleta ficticia",
                "confidence_level": FindingRecord.ConfidenceLevel.UNCONFIRMED,
                "internal_notes": "Borrador mínimo para demostrar que la app permite guardar información parcial.",
                "country": "México",
                "state": "Sin especificar",
                "municipality": "",
                "locality": "",
                "region": "",
                "place_type": "",
                "exact_location_restricted": "",
                "coordinates_restricted": "",
                "location_notes": "",
                "finding_date": None,
                "approximate_time": None,
                "date_notes": "",
                "temporal_range": "",
                "estimated_individuals": "",
                "conservation_status": "",
                "integrity": "",
                "exposure": "",
                "general_condition_notes": "",
                "estimated_sex": FindingRecord.EstimatedSex.UNKNOWN,
                "estimated_age": "",
                "estimated_height": "",
                "estimated_weight": "",
                "estimated_build": "",
                "skin_color": "",
                "hair": "",
                "facial_hair": "",
                "eyes": "",
                "physical_notes": "",
                "tattoos": "",
                "scars": "",
                "moles": "",
                "piercings": "",
                "prosthetics": "",
                "surgical_marks": "",
                "amputations": "",
                "distinctive_marks_notes": "",
                "braces": "",
                "dental_prosthetics": "",
                "missing_teeth": "",
                "dental_restorations": "",
                "dental_notes": "",
                "medical_notes": "",
                "notified_authority": "",
                "institutional_folio": "FOLIO-DEMO-008",
                "case_reference": "",
                "semefo": "",
                "institutional_notes": "Registro mínimo para mostrar captura parcial.",
                "contact_email": "",
                "created_by": demo_user,
            },
        ]

        created_count = 0
        reused_count = 0

        for data in records:
            record_code = data["record_code"]

            _, created_record = FindingRecord.objects.get_or_create(
                record_code=record_code,
                defaults=data,
            )

            if created_record:
                created_count += 1
            else:
                reused_count += 1

        self.stdout.write(self.style.SUCCESS("Usuario demo listo."))
        self.stdout.write(
            self.style.SUCCESS(
                f"Datos demo listos. Creados: {created_count}. Ya existentes: {reused_count}."
            )
        )