# Generated by Django 5.2.14 on 2026-05-16 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_code', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('in_review', 'En revisión'), ('restricted', 'Restringido'), ('closed', 'Cerrado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('finding_type', models.CharField(choices=[('body', 'Cuerpo'), ('bone_remains', 'Restos óseos'), ('human_fragment', 'Fragmento humano'), ('other', 'Otro'), ('unknown', 'Desconocido')], default='unknown', max_length=30)),
                ('source', models.CharField(blank=True, help_text='Fuente general del dato: observación directa, documento, autoridad, testimonio u otra.', max_length=150)),
                ('confidence_level', models.CharField(choices=[('confirmed', 'Confirmado'), ('probable', 'Probable'), ('unconfirmed', 'No confirmado')], default='unconfirmed', max_length=30)),
                ('country', models.CharField(default='México', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('locality', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('place_type', models.CharField(blank=True, max_length=100)),
                ('exact_location_restricted', models.TextField(blank=True)),
                ('coordinates_restricted', models.CharField(blank=True, max_length=100)),
                ('location_notes', models.TextField(blank=True)),
                ('finding_date', models.DateField(blank=True, null=True)),
                ('approximate_time', models.TimeField(blank=True, null=True)),
                ('date_notes', models.TextField(blank=True)),
                ('estimated_individuals', models.CharField(blank=True, max_length=100)),
                ('conservation_status', models.CharField(blank=True, max_length=100)),
                ('integrity', models.CharField(blank=True, max_length=100)),
                ('exposure', models.CharField(blank=True, max_length=100)),
                ('general_condition_notes', models.TextField(blank=True)),
                ('estimated_sex', models.CharField(choices=[('woman', 'Mujer'), ('man', 'Hombre'), ('undetermined', 'Indeterminado'), ('unknown', 'Desconocido')], default='unknown', max_length=30)),
                ('estimated_age', models.CharField(blank=True, max_length=100)),
                ('estimated_height', models.CharField(blank=True, max_length=100)),
                ('estimated_weight', models.CharField(blank=True, max_length=100)),
                ('estimated_build', models.CharField(blank=True, max_length=100)),
                ('skin_color', models.CharField(blank=True, max_length=100)),
                ('hair', models.CharField(blank=True, max_length=255)),
                ('facial_hair', models.CharField(blank=True, max_length=255)),
                ('eyes', models.CharField(blank=True, max_length=100)),
                ('physical_notes', models.TextField(blank=True)),
                ('tattoos', models.TextField(blank=True)),
                ('scars', models.TextField(blank=True)),
                ('moles', models.TextField(blank=True)),
                ('piercings', models.TextField(blank=True)),
                ('prosthetics', models.TextField(blank=True)),
                ('surgical_marks', models.TextField(blank=True)),
                ('distinctive_marks_notes', models.TextField(blank=True)),
                ('dental_notes', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('institutional_notes', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de hallazgo',
                'verbose_name_plural': 'Registros de hallazgos',
                'ordering': ['-created_at'],
            },
        ),
    ]
